when:
  - path:
      include: ['.woodpecker/php.yaml', 'php/**']
  - event: cron

matrix:
  PHP_VERSION:
    - 8.1
    - 8.2
    - 8.3

steps:
  docker-build:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: codeberg.org/${CI_REPO_OWNER}/devcontainer/php
      dockerfile: php/Dockerfile
      tag: ${PHP_VERSION}
      registry: codeberg.org
      dry-run: true
      build_args_from_env:
        - PHP_VERSION
      output: type=oci,dest=${CI_REPO_OWNER}-php.tar
  
  docker-push:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: codeberg.org/${CI_REPO_OWNER}/devcontainer/php
      dockerfile: php/Dockerfile
      tags: ${PHP_VERSION},${PHP_VERSION}-${CI_COMMIT_SHA:0:8}
      registry: codeberg.org
      dry-run: false
      username: ${CI_REPO_OWNER}
      password:
        from_secret: docker_password
      build_args_from_env:
        - PHP_VERSION
    when:
      - event: [push, tag, deployment, release]
        branch: main
      - event: cron