matrix:
  PHP_VERSION:
    - 8.1
    - 8.2
    - 8.3

steps:
  docker-build:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: codeberg.org/${CI_REPO_OWNER}/devcontainer
      dockerfile: php/Dockerfile
      tag: rotespferd/php:${PHP_VERSION}
      registry: codeberg.org
      dry-run: true
      build_args:
        - PHP_VERSION: ${PHP_VERSION}
  
  docker-push:
    image: debian
    commands:
      - echo "Docker push"