matrix:
  PHP_VERSION:
    - 8.1
    - 8.2
    - 8.3

steps:
  build:
    image: docker
    commands:
      - docker build --build-arg PHP_VERSION=${PHP_VERSION} -t rotespferd/php:${PHP_VERSION} php
  push:
    image: debian
    commands:
      - echo "Docker push"