matrix:
  PHP_VERSION:
    - 8.1
    - 8.2
    - 8.3

steps:
  docker-build:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: codeberg.org/${CI_REPO_OWNER}/devcontainer/php
      dockerfile: php/Dockerfile
      tag: ${PHP_VERSION}
      registry: codeberg.org
      dry-run: true
      output: type=oci,dest=${CI_REPO_OWNER}-php.tar
      build_args:
        - <<: *PHP_VERSION
  
  docker-push:
    image: debian
    commands:
      - echo "Docker push"